# Source - https://stackoverflow.com/questions/70192495/what-node-version-used-if-not-specified-it-in-github-actions
# Posted by sho
# Retrieved 4/30/2026, License - CC BY-SA 4.0

- name: Set up Node js
  uses: actions/setup-node@v6
  width:
     node-version: 24
